In [4]:
import os
import pandas as pd

# Load the data
data_path = os.path.join(os.path.dirname(os.getcwd()), 'data', 'NSL_regular_season_data_2.csv')
print(data_path)
data = pd.read_csv(data_path)

/workspaces/Wharton-HS-Competition-Soccer-Playoff-Predictions/data/NSL_regular_season_data_2.csv

In [7]:
# Find the rankings of the teams
d = {}
for i in range(len(data)):
    winner, loser, tie1, tie2 = '', '', '', ''
    if data['HomeScore'][i] > data['AwayScore'][i]:
        winner = data['HomeTeam'][i]
        loser = data['AwayTeam'][i]
    elif data['HomeScore'][i] < data['AwayScore'][i]:
        winner = data['AwayTeam'][i]
        loser = data['HomeTeam'][i]
    else:
        tie1 = data['HomeTeam'][i]
        tie2 = data['AwayTeam'][i]
    if winner:
        if winner not in d:
            d[winner] = [1, 0, 0]
        else:
            d[winner][0] += 1
    if loser:
        if loser not in d:
            d[loser] = [0, 1, 0]
        else:
            d[loser][1] += 1
    if tie1:
        if tie1 not in d:
            d[tie1] = [0, 0, 1]
        else:
            d[tie1][2] += 1
    if tie2:
        if tie2 not in d:
            d[tie2] = [0, 0, 1]
        else:
            d[tie2][2] += 1

# Create a dataframe from the dictionary
df = pd.DataFrame.from_dict(d, orient='index')
df.columns = ['Wins', 'Losses', 'Ties']
df['WinPct'] = df['Wins'] / (df['Wins'] + df['Losses'] + df['Ties'])

# Order the data alphabetically
df = df.sort_index()
df

     Wins  Losses  Ties    WinPct
ALB     9      15    10  0.264706
ANC    20       7     7  0.588235
AUG    19       7     8  0.558824
BAK    11      14     9  0.323529
BOI    11      12    11  0.323529
CHM     9      12    13  0.264706
DES    13      13     8  0.382353
DOV    14      12     8  0.411765
EUG    12      15     7  0.352941
FAR    20      11     3  0.588235
FOR    12      16     6  0.352941
JAC    17       7    10  0.500000
LAR    18      10     6  0.529412
LEX    13      12     9  0.382353
LRO    15      11     8  0.441176
MAN     8      15    11  0.235294
MOB    10      14    10  0.294118
OAK    15      11     8  0.441176
PRO    17      12     5  0.500000
REN    12      13     9  0.352941
SAS    14      12     8  0.411765
SFS    15       9    10  0.441176
SJU     6      20     8  0.176471
SPR    14      11     9  0.411765
TAC     7      23     4  0.205882
TOL    14      14     6  0.411765
TUC     9      19     6  0.264706
WIC     8      15    11  0.235294

In [8]:
# Save the data
df.to_csv(os.path.join(os.path.dirname(os.getcwd()), 'data', 'NSL_rankings.csv'))